export const GET_BOOKS_REQUEST = 'GET_BOOKS_REQUEST';
export const GET_BOOKS_FAILURE = 'GET_BOOKS_FAILURE';
export const GET_BOOKS_SUCCESS = 'GET_BOOKS_SUCCESS';
export const SET_BOOKS_CATEGORY = 'SET_BOOKS_CATEGORY';
export const SET_BOOKS_SELECTED = 'SET_BOOKS_SELECTED';

export const GET_FILTERS = 'GET_FILTERS';
export const SET_FILTERS = 'SET_FILTERS';
